general {
    hide_cursor = true
    ignore_empty_input = false
    immediate_render = true
}

background {
    monitor =
    color = rgba(000000ff)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgba(00000000)
    outer_color = rgba(ffffffff)
    font_color = rgba(ffffffff)
    placeholder_text = Password...
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 32
    color = rgba(ffffffff)
    position = 0, 100
    halign = center
    valign = center
}

